V2023.10
zephyrproject-rtos/libmetal pull request #22
Opened 2023-11-21 14:15 UTC by arnopo

Update libmetal to v2023.10 release + alignement on libmetal commit f3f365d "zephyr: use k_cpu_idle instead of arch_cpu_idle"

2023-11-21 14:32 UTC, arnopo commented
PR created for test in zephyr repo:
https://github.com/zephyrproject-rtos/zephyr/pull/65523

2023-11-22 10:11 UTC, carlocaione approved these changes

2023-11-22 10:36 UTC, carlescufi approved these changes

2023-11-22 10:38 UTC, carlescufi requested changes
There are test failures in the integration PR.

2023-12-14 16:17 UTC, arnopo commented
> There are test failures in the integration PR.

Solved

2023-12-14 18:37 UTC, carlescufi approved these changes

2023-12-14 18:37 UTC, merged